server:
  port: 18088

telegram:
  bot:
    username: ""
    token: "7589476199:xxxx"
    admins: 201728830
    base: https://api.telegram.org/bot
    webapp-url: https://xxx.xx.com  # 必须是https协议，需要使用nginx等反向代理该服务

app:
  chars-per-page: 3000

spring:
  datasource:
    url: jdbc:sqlite:data/epubbot.db
    driver-class-name: org.sqlite.JDBC
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false