server:
  port: 18088

telegram:
  bot:
    username: "MyTestEpubBot"
    token: "8220404450:xxxxx"
    admins: 123123123
    base: "https://api.telegram.org"
    webapp-url: https://test.com

app:
  chars-per-page: 3000

spring:
  datasource:
    url: jdbc:sqlite:data/epubbot.db?journal_mode=WAL&busy_timeout=5000
    driver-class-name: org.sqlite.JDBC
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false

cloud:
  r2:
    access-key: ${CLOUD_R2_ACCESS_KEY:your-access-key}
    secret-key: ${CLOUD_R2_SECRET_KEY:your-secret-key}
    account-id: ${CLOUD_R2_ACCOUNT_ID:your-account-id}
    bucket-name: ${CLOUD_R2_BUCKET_NAME:epub-storage}
    public-domain: ${CLOUD_R2_PUBLIC_DOMAIN:your-public-domain}