server:
  port: 18088

telegram:
  bot:
    username: "MyTestEpubBot"
    token: "8220404450:xxxxx"
    admins: 123123123
    base: "https://api.telegram.org"
    webapp-url: https://test.com

app:
  chars-per-page: 3000

spring:
  datasource:
    url: jdbc:sqlite:data/epubbot.db
    driver-class-name: org.sqlite.JDBC
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false

cloud:
  r2:
    access-key: "07a2bfb8cb2d9234e37efc5affdafa47"
    secret-key: "93c13cf0b3bb4ffe9db46cdeaff81d9c54af2cdc96018d2fad4343ce11e59b35"
    account-id: "fa29c8cdcb9bd46b60d72d2a6caf0ac3"
    bucket-name: "epub-storage"
    public-domain: "https://epub.8void.sbs/"