server:
  port: 18088

telegram:
  bot:
    username: ""
    token: "7589476199:xxxx"
    admins: 201728830
    base: "http://47.243.197.2:8081/bot"
    webapp-url: https://xx.xx.com/app

telegraph:
  access-token: ""
  author-name: "EpubReaderBot"

app:
  chars-per-page: 3000