server:
  port: 18088

telegram:
  bot:
    username: "MyTestEpubBot"
    token: "8220404450:xxxxx"
    admins: 123123123
    base: "https://api.telegram.org"
    webapp-url: https://test.com

app:
  chars-per-page: 3000

spring:
  datasource:
    url: jdbc:sqlite:data/epubbot.db
    driver-class-name: org.sqlite.JDBC
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false

cloud:
  r2:
    access-key: "access-key"
    secret-key: "secret-key"
    account-id: "account-id"
    bucket-name: "epub-storage"
    public-domain: "https://your.domain.com/"